/* This file was generated by SableCC (http://www.sablecc.org/). */

package mini.node;

import mini.analysis.*;

@SuppressWarnings("nls")
public final class AFloatTerm extends PTerm
{
    private TFloatconst _floatconst_;

    public AFloatTerm()
    {
        // Constructor
    }

    public AFloatTerm(
        @SuppressWarnings("hiding") TFloatconst _floatconst_)
    {
        // Constructor
        setFloatconst(_floatconst_);

    }

    @Override
    public Object clone()
    {
        return new AFloatTerm(
            cloneNode(this._floatconst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatTerm(this);
    }

    public TFloatconst getFloatconst()
    {
        return this._floatconst_;
    }

    public void setFloatconst(TFloatconst node)
    {
        if(this._floatconst_ != null)
        {
            this._floatconst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._floatconst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._floatconst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._floatconst_ == child)
        {
            this._floatconst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._floatconst_ == oldChild)
        {
            setFloatconst((TFloatconst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
