/* This file was generated by SableCC (http://www.sablecc.org/). */

package mini.node;

import mini.analysis.*;

@SuppressWarnings("nls")
public final class AIfelseStmt extends PStmt
{
    private PIfelse _ifelse_;

    public AIfelseStmt()
    {
        // Constructor
    }

    public AIfelseStmt(
        @SuppressWarnings("hiding") PIfelse _ifelse_)
    {
        // Constructor
        setIfelse(_ifelse_);

    }

    @Override
    public Object clone()
    {
        return new AIfelseStmt(
            cloneNode(this._ifelse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfelseStmt(this);
    }

    public PIfelse getIfelse()
    {
        return this._ifelse_;
    }

    public void setIfelse(PIfelse node)
    {
        if(this._ifelse_ != null)
        {
            this._ifelse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifelse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifelse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifelse_ == child)
        {
            this._ifelse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifelse_ == oldChild)
        {
            setIfelse((PIfelse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
