/* This file was generated by SableCC (http://www.sablecc.org/). */

package mini.node;

import mini.analysis.*;

@SuppressWarnings("nls")
public final class AOutputStmt extends PStmt
{
    private POutput _output_;

    public AOutputStmt()
    {
        // Constructor
    }

    public AOutputStmt(
        @SuppressWarnings("hiding") POutput _output_)
    {
        // Constructor
        setOutput(_output_);

    }

    @Override
    public Object clone()
    {
        return new AOutputStmt(
            cloneNode(this._output_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOutputStmt(this);
    }

    public POutput getOutput()
    {
        return this._output_;
    }

    public void setOutput(POutput node)
    {
        if(this._output_ != null)
        {
            this._output_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._output_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._output_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._output_ == child)
        {
            this._output_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._output_ == oldChild)
        {
            setOutput((POutput) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
